#!/bin/bash
hicFile=$1
chromSizes=$2
nChromes=$3
binSizes=$4
absFile="${hicFile}.abs.bed"


mkdir $hicFile"_temp"
mkdir $hicFile"_CaTCH"


chmod u+x hicpro2catch.sh
chmod u+x RemapAllMatrices


for i in $(seq 1 $nChromes);
do
		echo Constructing interaction matrices for chromosome $i...
		java -jar juicer_tools_1.11.09_jcuda.0.8.jar dump observed KR  $hicFile $i $i BP 5000 $hicFile"_temp"/$i.$i.matrix
done

python3 Create_Abs_Bed.py $hicFile $chromSizes $binSizes
./RemapAllMatrices $absFile $hicFile


mv hicpro2catch.sh $hicFile"_CaTCH"

for filename in $hicFile"_temp"/*.sorted.matrix; do
	echo Reformatting $filename for insulation score algorithm ...
	./$hicFile"_CaTCH"/hicpro2catch.sh -i $filename -b $binSizes -f $absFile
done

#cp *.CaTCH $hicFile"_CaTCH"

for filename in $hicFile"_CaTCH"/*.CaTCH; do
	echo Running Recipricol Insulation Score Algorithm for $filename ...
	touch "${filename}.nClusters"
	touch "${filename}.clusters"
#	Rscript CallCaTCH.R $filename "${filename}.nClusters" "${filename}.clusters"
done



for filename in $hicFile"_CaTCH"/*.clusters; do
	echo Converting $filename to .bed file...
#	python3 InsulationsToBed.py $filename $chromSizes $binSizes
done

echo Aggregating and sorting matrix...
#cat $hicFile"_CaTCH"/*.bed > "${hicFile}.bed"
#bedtools sort -i "${hicFile}.bed" > "${hicFile}.sorted.bed"

echo Converting to .Bedpe file...
#python3 BedToBedpe.py "${hicFile}.sorted.bed"

cat $hicFile"_CaTCH"/*.clusters > $hicFile"_CaTCH"/allClusters.cluster
echo Generating TAD Quality graphs...
mkdir $hicFile"_CaTCH"/results
./TADQualityAnalysis $hicFile"_CaTCH"/allClusters.cluster $hicFile".sorted.bedpe" $hicFile"_CaTCH"/results/
