#!/bin/bash

matrixDirectory=$1
sizes=$2
absFile=$3
binName=$4


matrixDirectory=$(realpath $matrixDirectory)

for filename in $matrixDirectory/*.matrix; do
	echo converting $filename to .my5C ....
	python3 matrix2my5C.py $filename $sizes $absFile $binName
done

xpwd=$(pwd)


cp matrix2insulation.pl $matrixDirectory
cd $matrixDirectory
for filename in $matrixDirectory/*.my5c; do
        echo calculating insulation for $filename ....
	perl matrix2insulation.pl -i $filename
done

cd $xpwd


echo Aggregating and sorting matrix...
cat *.bed > $matrixDirectory/aggregated.bed
python3 BoundsToTADS.py $matrixDirectory/aggregated.bed $sizes
bedtools sort -i $absFile_reversed.bed > $absFile.sorted.bed

echo Converting to .Bedpe file...
python3 BedToBedpe.py $absFile.sorted.bed
