#!/bin/bash

matrixDirectory=$1
sizes=$2
absFile=$3
binName=$4


matrixDirectory=$(realpath $matrixDirectory)

for filename in $matrixDirectory/*.matrix; do
	echo converting $filename to .my5C ....
	python3 matrix2my5C.py $filename $sizes $absFile $binName
done

xpwd=$(pwd)


cp matrix2insulation.pl $matrixDirectory
cd $matrixDirectory
rm file.swarm
for filename in $matrixDirectory/*.my5c; do
        echo calculating insulation for $filename ....
	echo perl matrix2insulation.pl -v -i $filename >> $matrixDirectory/file.swarm
done


swarm -g 200 -t 50 --module bedtools,R --time 72:00:00 --merge-output -f $matrixDirectory/file.swarm
cd $xpwd


#echo Aggregating and sorting matrix...
#cat $matrixDirectory/*.bed > $matrixDirectory/dekkerTADs.bed
#python3 BoundsToTADS.py $matrixDirectory/dekkerTADs.bed $sizes
#bedtools sort -i $matrixDirectory/dekkerTADs_reversed.bed > $matrixDirectory/dekkerTADs.sorted.bed

#echo Converting to .Bedpe file...
#python3 BedToBedpe.py $matrixDirectory/dekkerTADs.sorted.bed
