#!/bin/bash
# bash to run full pipeline to turn interactions text file into filtered viewpoints for each territory

TERRITORYFILE=$1
INTERACTIONSFILE=$2
CHROMSIZESFILE=$3
PICKLEFILE="$INTERACTIONSFILE.pkl"
READER_OUTPUT="$INTERACTIONSFILE.quality.txt"
echo $READER_OUTPUT
echo Running quality analysis on $INTERACTIONSFILE. This will take some time.
python3 InteractionScore.py $TERRITORYFILE $INTERACTIONSFILE $PICKLEFILE $READER_OUTPUT

echo Generating viewpoints .bed files for $INTERACTIONSFILE.
python3 EnhancedBed.py $PICKLEFILE "$TERRITORYFILE.pkl" "$INTERACTIONSFILE..bed" $READER_OUTPUT

for i in $INTERACTIONSFILE*.bed; do
	[ -f "$i" ] || break
	echo "Sorting $i ...."
	SORTED="$i.sorted.bed"
	bedtools sort -i $i > $SORTED
	python3 removeUnknownChroms.py $CHROMSIZESFILE $SORTED
	echo Generating .bedgraph files from $SORTED
	BEDGRAPH="$SORTED.bedgraph"
	bedtools genomecov -i $SORTED -g $CHROMSIZESFILE -bg > $BEDGRAPH
done
rm $INTERACTIONSFILE.pkl $TERRITORYFILE.pkl
